### ISSUE TITLE
Does hypercore support immutable drives?

### ISSUE THREAD

**Issue by casey** [holepunchto/hypercore#334]
BitTorrent torrents are immutable. It would be nice if hypercore had similar functionality, to support similar use cases.

**Comment by mafintosh** [comment]
Yep, the authentication is actually pluggable so implicitly already supported, but will make it clearer in the readme

**Comment by casey** [comment]
Nice! What's the DHT key for an immutable drive? Just a hash of the content?

**Comment by mafintosh** [comment]
Hash of a hash of the content so you still have the capability
