### ISSUE TITLE
Reticulum compatability?

### ISSUE THREAD

**Issue by samuk** [holepunchto/hypercore#338]
Two questions

1) Could I use my Reticulum Identity: https://github.com/markqvist/Reticulum/discussions/155#discussioncomment-4186004 to append to Hypercore logs?

2) Could I use https://reticulum.network/ as a transport for Hypercore?

**Comment by mafintosh** [comment]
HC supports ed25519 keys atm so depends on that. The transport stream can be any binary stream.

**Comment by samuk** [comment]
[ed25519](https://github.com/markqvist/Reticulum/blob/master/RNS/Cryptography/Ed25519.py) is supported so it looks like it would be compatible
