### ISSUE TITLE
Bundling hyper-ecosystem tools with rollup, possible?

### ISSUE THREAD

**Issue by zacharygriffee** [holepunchto/hypercore#358]
I have been using browserify very successfully on hypercore and all the other 'hyper tools' (my team has been calling it) and then bundling the browserify bundle with rollup; but I'd like to skip that browserify step to reduce maintenance burden. I'd really like to keep my project up-to-date with the regular updates everyone is doing on this project. 

If it's possible, any advice on this would be greatly appreciated.

**Comment by telamon** [comment]
Yes, i have a couple of svelte projects using hyper-protocol with a rollup-conf.js without browserify.

**Comment by zacharygriffee** [comment]
Forgot about this message, I did end up getting it to work few months back! Thank you for the response :).
