### ISSUE TITLE
createByteStream with range option tries to parse the range post 'valueEncoded' values.

### ISSUE THREAD

**Issue by zacharygriffee** [holepunchto/hypercore#457]
Figured I raise an issue about it just in case.

The expectation: createByteStream with range options {byteLength, byteOffset}  would get the bytes from the core in byte form, without the valueEncoding applied.

What happens: When the core's 'valueEncoding' configuration is applied, and the 'range options' of createByteStream is used, the byte stream tries to 'split' the decoded value and causes an error.  

```
const core = new Hypercore(RAM, {valueEncoding: "utf8"});
await core.append(b4a.from("123456789"));
for await(const entry of core.createByteStream({byteOffset: 2,byteLength: 3}) {
    //expect entry to be a buffer/uint8array with 345 but get an error trying to subarray the string decoded version if it.
}
```

![image](https://github.com/holepunchto/hypercore/assets/5599507/74176495-a9b2-4ced-8dad-41fe337f6c55)

**Comment by mafintosh** [comment]
Ah good point, it should force binary encoding. PR welcome
