### ISSUE TITLE
Entry Signature Getter

### ISSUE THREAD

**Issue by brucejaya** [holepunchto/hypercore#478]
In pre-v10 versions of Hypercore the `feed.signature([index], callback)` provided a simple way to access signatures associated with an entry. This functionality has now been removed and as far as I can tell (?) there is no way to access signatures without messing with the internals (which I really don't want to do). Signatures are extremely useful and should surely just fall under the umbrella of a primitive within the Hypercore protocol - are there obvious alternatives that I am missing? Cheers.

**Comment by mafintosh** [comment]
core.core.tree.signature

**Comment by mafintosh** [comment]
Only one sig exists

**Comment by brucejaya** [comment]
So it's no longer possible to lookup the signature for a specific entry? To associate a signature with an entry would ultimately be a question of bolt on logic

**Comment by mafintosh** [comment]
the latest signature signs everything (ie the root of the merkle tree). you can compute a tree proof get the sig of a single block from that
